import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

final scaffoldFinder = find.byType(Scaffold);
final centerFinder = find.byType(Center);
final cardFinder = find.byType(Card);
final singleChildScrollViewFinder = find.byType(SingleChildScrollView);
final paddingFinder = find.byType(Padding);
final formFinder = find.byType(Form);
final columnFinder = find.byType(Column);
final textFormFieldFinder = find.byType(TextFormField);
final textFieldFinder = find.byType(TextField);
final elevatedButtonFinder = find.byType(ElevatedButton);
final checkboxFinder = find.byType(Checkbox);
final snackBarFinder = find.byType(SnackBar);
final rowFinder = find.byType(Row);
final dismissibleFinder = find.byType(Dismissible);
final checkboxListTileFinder = find.byType(CheckboxListTile);
final listViewFinder = find.byType(ListView);
final bySubtypeFinder = find.bySubtype();
final appBarFinder = find.byType(AppBar);
final circularProgressIndicatorFinder = find.byType(CircularProgressIndicator);
final floatingActionButtonFinder = find.byType(FloatingActionButton);
