// Mocks generated by Mockito 5.4.2 from annotations
// in nonso/test/src/widgets/email_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'email_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [VerifyEmailFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyEmailFunction extends _i1.Mock
    implements _i2.VerifyEmailFunction {
  MockVerifyEmailFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(
    String? email,
    void Function(_i4.FirebaseAuthException)? errorCallback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            email,
            errorCallback,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ToLogoutFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockToLogoutFunction extends _i1.Mock implements _i2.ToLogoutFunction {
  MockToLogoutFunction() {
    _i1.throwOnMissingStub(this);
  }
}
